// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FeedbackFormModuleScssNamespace {
  export interface IFeedbackFormModuleScss {
    form: string;
    form__error: string;
    form__message: string;
  }
}

declare const FeedbackFormModuleScssModule: FeedbackFormModuleScssNamespace.IFeedbackFormModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FeedbackFormModuleScssNamespace.IFeedbackFormModuleScss;
};

export = FeedbackFormModuleScssModule;
