// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TextFieldModuleScssNamespace {
  export interface ITextFieldModuleScss {
    field: string;
    field__dash: string;
    field__error: string;
    field__input: string;
    'field__input-icon': string;
    field__label: string;
    input: string;
  }
}

declare const TextFieldModuleScssModule: TextFieldModuleScssNamespace.ITextFieldModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TextFieldModuleScssNamespace.ITextFieldModuleScss;
};

export = TextFieldModuleScssModule;
