// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TextareaModuleScssNamespace {
  export interface ITextareaModuleScss {
    _limit: string;
    container: string;
    'symbols-info': string;
  }
}

declare const TextareaModuleScssModule: TextareaModuleScssNamespace.ITextareaModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TextareaModuleScssNamespace.ITextareaModuleScss;
};

export = TextareaModuleScssModule;
