// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonPreloaderModuleScssNamespace {
  export interface IButtonPreloaderModuleScss {
    'ball-1': string;
    'ball-2': string;
    'ball-3': string;
    container: string;
    grow: string;
  }
}

declare const ButtonPreloaderModuleScssModule: ButtonPreloaderModuleScssNamespace.IButtonPreloaderModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonPreloaderModuleScssNamespace.IButtonPreloaderModuleScss;
};

export = ButtonPreloaderModuleScssModule;
