// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DateFieldModuleScssNamespace {
  export interface IDateFieldModuleScss {
    _focused: string;
    field: string;
    field__dash: string;
    field__error: string;
    field__input: string;
    'field__input-icon': string;
    field__label: string;
    input: string;
  }
}

declare const DateFieldModuleScssModule: DateFieldModuleScssNamespace.IDateFieldModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: DateFieldModuleScssNamespace.IDateFieldModuleScss;
};

export = DateFieldModuleScssModule;
