// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MaskFieldModuleScssNamespace {
  export interface IMaskFieldModuleScss {
    field: string;
    field__dash: string;
    field__error: string;
    field__input: string;
    'field__input-icon': string;
    field__label: string;
    input: string;
  }
}

declare const MaskFieldModuleScssModule: MaskFieldModuleScssNamespace.IMaskFieldModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MaskFieldModuleScssNamespace.IMaskFieldModuleScss;
};

export = MaskFieldModuleScssModule;
